### ISSUE TITLE
Aliases not working on server side rendering

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/nextjs-preact-demo#11]
When Next.js is bundling for server side rendering, all dependencies are externalized. So when you inspect the bundle output, you'll see that React is still used;

```
/***/ "react":
/*!************************!*\
  !*** external "react" ***!
  \************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("react");
```

**Comment by developit** [comment]
This should be okay, because those require() statements will be resolved to `preact/compat` by Node. Though I believe right now external dependencies that require React can end up with their own copy - to fix that we need to switch from npm aliases to `module-alias`.

**Comment by marvinhagemeister** [comment]
Just checked with current `master` and `react` is not present in any bundler or chunk 🎉
