### ISSUE TITLE
Integrate NextJS .babelrc in Webpack?

### ISSUE THREAD

**Issue by heymartinadams** [developit/nextjs-preact-demo#13]
Hi @developit! Somehow use of the [next.config.js](https://github.com/developit/nextjs-preact-demo/blob/master/next.config.js) file in a NextJS project causes the NextJS project to not read its `.babelrc` file. See here: https://github.com/zeit/next.js/issues/12190

Is this something NextJS needs to fix, or related to this custom-built file?

**Comment by developit** [comment]
I believe this is a bug that has now been fixed in Next.js - please re-open if its still an issue in the latest next!
