### ISSUE TITLE
The hot reloading works only with unnamed export default functions.

### ISSUE THREAD

**Issue by yassinebridi** [developit/nextjs-preact-demo#15]
The about components export it's function like this:
```jsx
export default () => (
  <main>
    <h1>About us</h1>
  </main>
);
```
but if i try to use it with any of the other export style:
```js
export default function About() {}
```
or
```js
const About = () => {}
export default About;
```
the hot reloading doesn't work.

**Comment by JoviDeCroock** [comment]
This is the case for Next 9.4 because named components are picked up by `react-refresh`, since these are `hot-accepted` modules they won't reload and `react-refresh` won't know how to reload them.

This will be fixed when we merge https://github.com/developit/nextjs-preact-demo/pull/16

**Comment by yassinebridi** [comment]
I have used it, and it works for my case, thanks for your help @JoviDeCroock,
i will close this for now.
