### ISSUE TITLE
How to update those linked packages?

### ISSUE THREAD

**Issue by muuvmuuv** [developit/nextjs-preact-demo#20]
I have never worked with linked package versions in yarn, how do I update those?

```
    "react": "github:preact-compat/react#1.0.0",
    "react-dom": "github:preact-compat/react-dom#1.0.0",
    "react-ssr-prepass": "npm:preact-ssr-prepass@^1.0.1"
```

**Comment by developit** [comment]
Hiya - the first two are just alias packages that contain no code. Releases for them are [here](https://github.com/preact-compat/react/releases), though they're unlikely to ever need to be updated.

The last one is a standard npm/yarn dependency, just with the name aliased. You can see version of the package here:
https://www.npmjs.com/package/preact-ssr-prepass

**Comment by developit** [comment]
They've been updated as of #21/#22.
