### ISSUE TITLE
Info about "or far lower with additional Webpack optimizations"

### ISSUE THREAD

**Issue by vvo** [developit/nextjs-preact-demo#4]
Hi there, in you README you say "or far lower with additional Webpack optimizations" about the size of the build.

Do you plan on going further and providing an example about that? Thanks!

**Comment by developit** [comment]
Heh - I have two whole projects I'm privately working on that will address this. Basically if you run the build and peek at the bundles, there's still a fair amount of dead code in them - particularly for first view. 

That being said, that comment in the README was from a time when this demo was 32kB, and as of Next.js 9.3 it's down to 21kB. There's definitely still more optimizations available, but half of them have already been done :)

**Comment by vvo** [comment]
Thanks! Appreciate the precision, will just close this so that's one issue less :D
