### ISSUE TITLE
'How to use' commands doesn't work. Small typo

### ISSUE THREAD

**Issue by bestwestern** [developit/nextjs-preact-demo#9]
![image](https://user-images.githubusercontent.com/3617433/78656774-2c491200-78c8-11ea-9fdc-9d5173e5e964.png)

**Comment by wiesson** [comment]
Hmm, Works on my machine - 

```
$ Dev git clone git@github.com:developit/nextjs-preact-demo    
Cloning into 'nextjs-preact-demo'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 43 (delta 17), reused 23 (delta 5), pack-reused 0
Receiving objects: 100% (43/43), 108.92 KiB | 1.18 MiB/s, done.
Resolving deltas: 100% (17/17), done.
```

**Comment by bestwestern** [comment]
apparently you have the proper permissions.
This works on my (any?) machine:
git clone https://github.com/developit/nextjs-preact-demo.git

**Comment by flashblaze** [comment]
> apparently you have the proper permissions.
> This works on my (any?) machine:
> git clone https://github.com/developit/nextjs-preact-demo.git

@bestwestern this happens due to SSH keys not being set. So cloning via HTTPS is the way to go. Hope that helps.

**Comment by developit** [comment]
I've switched the instructions to show the https URL for now.
